apiVersion: v1
kind: Service
metadata:
  name: netbox
  namespace: netbox
spec:
  selector:
    app: netbox
  sessionAffinity: ClientIP
  ports:
  - port: 80
    targetPort: 8000
    protocol: TCP
  type: ClusterIP
