apiVersion: v1
kind: ConfigMap
metadata:
  name: netbox
  namespace: netbox
data:
  # PASSWORD's has been passed by secret! ;] 
  PUID: "1000"
  PGID: "1000"
  SUPERUSER_EMAIL: brisa@brisolla.io
  ALLOWED_HOST: "*"
  # PostgreSQL configs
  DB_NAME: netbox
  DB_USER: netbox
  DB_HOST: netbox-postgres-postgresql.netbox
  DB_PORT: "5432"
  # Redis configs
  REDIS_HOST: redis
  REDIS_PORT: "6379"
  # LDAP auth configs
#  REMOTE_AUTH_ENABLED: 'True'
#  REMOTE_AUTH_BACKEND: netbox.authentication.LDAPBackend
  # ldap binding settings are stored in netbox-configmap-ldap.yml
